4
13B
NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 440, in <module>
    main()
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 219, in main
Traceback (most recent call last):
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 440, in <module>
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 440, in <module>
    main()
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 219, in main
    main()
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 219, in main
Traceback (most recent call last):
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 440, in <module>
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
    main()
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 219, in main
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
            obj = dtype(**inputs)
obj = dtype(**inputs)
  File "<string>", line 118, in __init__
    obj = dtype(**inputs)
  File "<string>", line 118, in __init__
obj = dtype(**inputs)  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1333, in __post_init__
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1333, in __post_init__

  File "<string>", line 118, in __init__
  File "<string>", line 118, in __init__
Traceback (most recent call last):
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 440, in <module>
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1333, in __post_init__
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1333, in __post_init__
    main()
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 219, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 118, in __init__
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1333, in __post_init__
    and (self.device.type != "cuda")
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1697, in device
    and (self.device.type != "cuda")
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1697, in device
    and (self.device.type != "cuda")
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1697, in device
    and (self.device.type != "cuda")
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1697, in device
    and (self.device.type != "cuda")
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1697, in device
Traceback (most recent call last):
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 440, in <module>
    return self._setup_devices
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    return self._setup_devices
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    main()
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 219, in main
    return self._setup_devices
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
    return self._setup_devices
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    obj = dtype(**inputs)
  File "<string>", line 118, in __init__
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1333, in __post_init__
        cached = self.fget(obj)cached = self.fget(obj)

  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1613, in _setup_devices
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1613, in _setup_devices
    cached = self.fget(obj)    
cached = self.fget(obj)  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1613, in _setup_devices

  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1613, in _setup_devices
    return self._setup_devices
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1613, in _setup_devices
    and (self.device.type != "cuda")
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1697, in device
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate`: Run `pip install --upgrade accelerate`
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate`: Run `pip install --upgrade accelerate`
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate`: Run `pip install --upgrade accelerate`
    return self._setup_devices
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate`: Run `pip install --upgrade accelerate`
    raise ImportError(
    cached = self.fget(obj)ImportError
: Using the `Trainer` with `PyTorch` requires `accelerate`: Run `pip install --upgrade accelerate`  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1613, in _setup_devices

    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate`: Run `pip install --upgrade accelerate`
Traceback (most recent call last):
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 440, in <module>
    main()
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 219, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 118, in __init__
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1333, in __post_init__
Traceback (most recent call last):
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 440, in <module>
    main()
  File "/Users/lisiyu/IdeaProjects/ALGO/llm_finetune/scripts/run_clm_sft_with_peft.py", line 219, in main
    and (self.device.type != "cuda")
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1697, in device
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 118, in __init__
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1333, in __post_init__
    return self._setup_devices
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1613, in _setup_devices
    and (self.device.type != "cuda")
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1697, in device
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate`: Run `pip install --upgrade accelerate`
    return self._setup_devices
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1613, in _setup_devices
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate`: Run `pip install --upgrade accelerate`
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 40763) of binary: /Users/lisiyu/opt/anaconda3/envs/py39/bin/python
2
7B
base_model: /app/original-weights/cn_llama_alpaca/7B
lora_model: /app/original-weights/finetuning-output/sft_lora_model
output_type: huggingface
output_dir: /app/original-weights/cn_llama_alpaca/123123
WARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
Traceback (most recent call last):
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/socket.py", line 792, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lisiyu/opt/anaconda3/envs/py39/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 726, in run
    self._record_worker_events(result)
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 757, in _record_worker_events
    record(self._construct_event(state, EventSource.WORKER, worker, raw_error))
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 798, in _construct_event
    "hostname": _get_fq_hostname(),
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 386, in _get_fq_hostname
    return socket.getfqdn(socket.gethostname())
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/socket.py", line 792, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
  File "/Users/lisiyu/opt/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 40747 got signal: 2
